### ISSUE TITLE
Salutations in letters

### ISSUE THREAD

**Issue by michael-77** [mgbennet/booker-t-washington_up-from-slavery#10]
I would generally amend
```
<p><span epub:type="z3998:salutation">Dear Sir:</span>... 
``` 
to 
```
<p epub:type="z3998:salutation">Dear Sir:</p>
<p>...
``` 
and use 

```
[epub|type~="z3998:salutation"]+p{
	text-indent: 0;
} 
```
to style it which will give a consistent look to the letters and improve the readability. Again you would probably put this in an [Editorial] commit

**Comment by mgbennet** [comment]
Not sure about this one. There are plenty of other SE books, like the recently released "Jeeves Stories", where we leave the salutation in the opening letter. Especially for short letters like the ones in this book, I don't think it adds a lot of readability to break the salutation to a separate line.

**Comment by michael-77** [comment]
Fair enough - it was an editorial suggestion ;-)
