### ISSUE TITLE
Chapter 5 [Editorial]

### ISSUE THREAD

**Issue by michael-77** [mgbennet/booker-t-washington_up-from-slavery#5]
Consider whether 

> would receive “a call to preach” 

should be 

> would receive a “call to preach”

If you agree then again an [Editorial] commit would be appropriate.

**Comment by mgbennet** [comment]
I don't think I agree. I feel like it's more accurate to the way the phrase is used to include the "a" in the quotation marks. Also I'd prefer to stick as close to the scans as possible.

**Comment by michael-77** [comment]
Ok!
