### ISSUE TITLE
Long Speech in Chapter 14

### ISSUE THREAD

**Issue by michael-77** [mgbennet/booker-t-washington_up-from-slavery#7]
My inclination would be to leave it in a normal indented blockquote and then drop the `<hr/>` tags above and below which we wouldn't really want to use to separate out a blockquote.

In short it would mean removing 
```
/* Styling for extended speech in chapter 14 */
#chapter-14 > blockquote:first-of-type{
	margin: 0;
}
```
from `local.css` and the `<hr/>` tags from `chapter-14.xhtml`

**Comment by mgbennet** [comment]
I'm a little hesitant to do this due to the shear length of the thing. I asked about this in the thread and Alex suggested setting the margins to 0 if the block quote was so long that the margins would be distracting. That said I'm not married to the current layout and can be persuaded either way.

**Comment by michael-77** [comment]
My view would be that we appear to end up using <hr/> tags merely to bookend a speech rather than using them for a change in scene within the chapter. 

I don't think that the indentation is particularly distracting and gives a decent reminder that we are within the speech. 

@acabal, do you have any further thoughts?

**Comment by acabal** [comment]
`<hr>` means 'thematic break' so it should not be used to offset blockquotes.

This particular one doesn't seem *that* long. I'd leave it as a regular blockquote.

**Comment by mgbennet** [comment]
Alright, sounds good. Done.
