### ISSUE TITLE
<header> elements

### ISSUE THREAD

**Issue by michael-77** [mgbennet/booker-t-washington_up-from-slavery#8]
`<header>` seems to always be styled to the right (whether in letter or article) so just style directly and once which means you can remove a lot of the extra css targetting elements nested within headers:
```
header{
	text-align: right;
}
```

**Comment by mgbennet** [comment]
Wouldn't that hit the headers in the colophon and imprint?

**Comment by michael-77** [comment]
```
section[epub|type~="chapter"] header{
	text-align: right;
}
```
would select all the headers in the chapters.

**Comment by mgbennet** [comment]
Sure, that cleans up the css a little.
